server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: pms
    password: pms!2
    url: jdbc:mariadb://115.85.183.34:3306/iteyesfintech
  sql:
    init:
      encoding: utf-8
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    default: local # 기본 환경을 dev로
  devtools:
    livereload:
      enabled: true

mybatis:
  type-aliases-package: com.iteyes.**.dto
  mapper-locations: /mapper/**/*.xml

systemProp:
  org:
    gradle:
      internal:
        publish:
          checksums:
            insecure: true

logging:
  config-classpath: log4j2.xml

jwt:
  salt: MYSALT
  expmin: 5

file-upload-dir: C:\\fileupload\\