server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  # 사용할 JDBC 드라이버
    url: jdbc:mysql://localhost:3306/pms  # 데이터베이스의 URL
    username: root  # 데이터베이스에 연결할 사용자 이름
    password: Cjs414ghqja!  # 데이터베이스에 연결할 비밀번호
  sql:
    init:
      encoding: utf-8
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    default: local # 기본 환경을 dev로
  devtools:
    livereload:
      enabled: true

mybatis:
  type-aliases-package: com.iteyes.**.dto
  mapper-locations: /mapper/**/*.xml

systemProp:
  org:
    gradle:
      internal:
        publish:
          checksums:
            insecure: true

logging:
  config-classpath: log4j2.xml

jwt:
  salt: MYSALT
  expmin: 5

file-upload-dir: D:\\fileupload\\
upload-form-dir: D:\\fileupload\\uploadForm\\
