server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: pms
    password: pms!2
    url: jdbc:mariadb://115.85.183.34:3306/iteyesfintech
  sql:
    init:
      encoding: utf-8
  main:
    allow-bean-definition-overriding: true

  config:
    activate:
      on-profile: dev


jwt:
  salt: MYSALT
  expmin: 5

file-upload-dir: C:\\fileupload\\